# -*- coding: utf-8 -*-
"""early_predictors_startup_growth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkJHfhJ02Q3_12JH31IG5ISPZCo3NUNZ

**APPENDIX A**
"""

# Load the libraries #
import pandas as pd

# Load both datasets #
inv = pd.read_csv('Investors_DS1.csv')
fund = pd.read_csv('Startups_funding_DS2.csv')

print("=== Investors_DS1 - (inv) head ===")
print(inv.head())

print("\n=== Investors_DS1 - (inv) columns ===")
print(inv.columns)

print("=== Startups_funding_DS2 - (fund) head ===")
print(fund.head())

print("\n= Startups_funding_DS2 - (fund) column ===")
print(fund.columns)

# Drop unnecessary index-like columns from funding dataset #
fund = fund.drop(columns=['Unnamed: 0', 'Sr No'])

"""**APPENDIX B**"""

# Normalize Startup Names #
inv['Company_clean'] = inv['Company'].str.lower().str.strip()
fund['startup_clean'] = fund['startup'].str.lower().str.strip()

print("=== Sample of cleaned names from inv ===")
print(inv[['Company','Company_clean']].head())

print("=== Sample of cleaned names from fund ===")
print(fund[['startup','startup_clean']].head())

# Clean founders column and extract founder_count properly #
inv['Founders_clean'] = inv['Founders'].astype(str).str.replace('\n',' ', regex=True).str.strip()

inv['founders_count'] = inv['Founders_clean'].apply(lambda x: len([f for f in x.split(',') if f.strip() != '']))

print(inv[['Company','Founders_clean','founders_count']].head())

# Create Series A Flag #
fund['SeriesA_flag'] = fund['round'].apply(lambda x: 1 if 'Series A' in str(x) else 0)

# Reduce to startup level: if ANY round is Series A -> 1 #
seriesA = fund.groupby('startup_clean')['SeriesA_flag'].max().reset_index()

# Merge investor dataset with Series A table #
merged = inv.merge(seriesA, left_on='Company_clean', right_on='startup_clean', how='left')

merged['SeriesA_flag'] = merged['SeriesA_flag'].fillna(0)

print(merged[['Company','Company_clean','founders_count','SeriesA_flag']].head())

# Feature engineering for early funding indicators #

# Number of funding rounds per startup #
fund_rounds = fund.groupby('startup_clean')['round'].count().reset_index()
fund_rounds.columns = ['startup_clean', 'num_funding_rounds']

# Total early funding amount per startup #
fund_amount = fund.groupby('startup_clean')['round'].count().reset_index()
fund_amount.columns = ['startup_clean', 'early_total_funding']

# Number of unique investors #
fund['investors_clean'] = fund['investors'].astype(str).str.replace('\n', ' ', regex=True)
fund['investor_list'] = fund['investors_clean'].apply(lambda x: [i.strip() for i in x.split(',')])

unique_inv = fund.explode('investor_list')
unique_inv = unique_inv.groupby('startup_clean')['investor_list'].nunique().reset_index()
unique_inv.columns = ['startup_clean','unique_investors_count']

"""**APPENDIX C**"""

# Merge all engineered features into the main dataset #
merged = merged.merge(fund_rounds, on='startup_clean', how='left')
merged = merged.merge(fund_amount, on='startup_clean', how='left')
merged = merged.merge(unique_inv, on='startup_clean', how='left')

# Filling in the missing values #
merged[['num_funding_rounds','early_total_funding','unique_investors_count']] = \
merged[['num_funding_rounds', 'early_total_funding', 'unique_investors_count']].fillna(0)

merged.to_csv("startup_master_dataset.csv", index=False)

merged.head()
merged.info()
merged.describe()
merged['SeriesA_flag'].value_counts()

"""**APPENDIX D**"""

# Basic EDA on final merged dataset #

# Structure of dataset #
print("=== Dataset Info ===")
print(merged.info())

# Summary Statistics #
print("=== Summary Statistics ===")
print(merged.describe(include='all'))

# Count of series A vs non Series A startups #
print("=== Series A Distribution ===")
print(merged['SeriesA_flag'].value_counts())

print("=== Series A Percentage ===")
print(merged['SeriesA_flag'].value_counts(normalize=True) * 100)

# Quick checks of predictor variables #
print("=== Sample Early Indicators ===")
print(merged.groupby('SeriesA_flag')[['founders_count',
                                      'num_funding_rounds',
                                      'early_total_funding',
                                      'unique_investors_count']].head())

# Grouped means (useful for findings) #
print("=== Grouped Means by Series A Outcome ===")
print(merged.groupby('SeriesA_flag')[['founders_count',
                                      'num_funding_rounds',
                                      'early_total_funding',
                                      'unique_investors_count']].mean())

"""**ALL VISUALIZATIONS**"""

# Creating visuals that can be put in findings #

# Color Palette
import matplotlib.pyplot as plt

COLOR_NO_A = "#1F2933" # dark charcoal
COLOR_A = "#0D9488" # muted teal
BG_COLOR = "F7FCFE" # background color

labels = ["No Series A", "Series A"]
colors = [COLOR_NO_A, COLOR_A]

import matplotlib.pyplot as plt

# Redefine BG_COLOR with the correct hex prefix for this cell's execution
BG_COLOR = "#F7FCFE" # background color

# Bar Chart - H1: Founder Count vs Series A #
fig, ax = plt.subplots(figsize = (7,4), facecolor = BG_COLOR)
ax.set_facecolor(BG_COLOR)

values = (
    merged.groupby("SeriesA_flag")["founders_count"]
    .mean()
    .reindex([0,1])
)

ax.bar(labels, values, color = colors)
ax.set_title("Average Founding Team Size by Series A Outcome")
ax.set_xlabel("Series A Outcome")
ax.set_ylabel("Average Founder Count")

plt.tight_layout()
plt.show()

# Boxplot - H2: Early Total Funding vs Series A #
fig, ax = plt.subplots(figsize = (7,4), facecolor = BG_COLOR)
ax.set_facecolor(BG_COLOR)

data = [
    merged[merged["SeriesA_flag"] == 0]["early_total_funding"].dropna(),
    merged[merged["SeriesA_flag"] == 1]["early_total_funding"].dropna()
]

box = ax.boxplot(
    data,
    patch_artist=True,
    labels=["No Series A", "Series A"]
)

box["boxes"][0].set_facecolor(COLOR_NO_A)
box["boxes"][1].set_facecolor(COLOR_A)

ax.set_title("Distribution of Early Funding by Series A Outcome")
ax.set_xlabel("Series A Outcome")
ax.set_ylabel("Early Total Funding")

plt.tight_layout()
plt.show()

# Lollipop Stems + Dots - Number of Funding Rounds vs Series A #
vals = (
    merged.groupby("SeriesA_flag")["num_funding_rounds"]
    .mean()
    .reindex([0,1])
    .values
)

y_pos = [0,1]

fig, ax = plt.subplots(figsize = (7,3.8), facecolor = BG_COLOR)
ax.set_facecolor(BG_COLOR)

for y, v, c, in zip(y_pos, vals, colors):
  ax.hlines(y=y, xmin=0, xmax=v, color=c, linewidth=3) # stem
  ax.plot(v,y,"o",color=c, markersize=10)

ax.set_yticks(y_pos)
ax.set_yticklabels(labels)
ax.set_xlabel("Average Number of Funding Rounds")
ax.set_title("Funding Round Frequency by Series A Outcome")

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

ax.set_xlim(left=0)

plt.tight_layout()
plt.show()

# Bar Chart - H4: Unique Investors vs Series A #
fig, ax = plt.subplots(figsize = (7,4), facecolor = BG_COLOR)
ax.set_facecolor(BG_COLOR)

values = (
    merged.groupby("SeriesA_flag")["unique_investors_count"]
    .mean()
    .reindex([0,1])
)

ax.bar(labels, values, color=colors)
ax.set_title("Average Unique Investor Count by Series A Outcome")
ax.set_xlabel("Series A Outcome")
ax.set_ylabel("Average Number of Unique Investors")

plt.tight_layout()
plt.show()

# Bar Chart - H5: Top Cities for Series A Startups #
city_col = 'City'
seriesA_df = merged[merged['SeriesA_flag'] == 1]

city_counts = (
    seriesA_df['City']
    .dropna()
    .value_counts()
    .head(10)
)

print(city_counts)